module.exports = {
  extends: ["stylelint-config-prettier"],
  rules: {
    "at-rule-no-unknown": [
      true,
      {
        ignoreAtRules: [
          "extend",
          "at-root",
          "debug",
          "warn",
          "error",
          "if",
          "else",
          "for",
          "each",
          "while",
          "mixin",
          "include",
          "content",
          "return",
          "tailwind",
          "apply",
          "responsive",
          "variants",
          "screen",
          "function",
        ],
      },
    ],
    "no-duplicate-selectors": null,
    "declaration-block-trailing-semicolon": null,
    "no-descending-specificity": null,
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    // "selector-class-pattern": "^[a-zA-Z][a-zA-Z0-9-]+$",
    // "selector-id-pattern": "^[a-zA-Z][a-zA-Z0-9-]+$",
  },
};
